USE MusicShop;

CREATE TABLE Stock
(
	ID UNIQUEIDENTIFIER DEFAULT NEWID()
	CONSTRAINT PK_Stock PRIMARY KEY,

	ID_Composition UNIQUEIDENTIFIER NOT NULL
	CONSTRAINT FK_Composition FOREIGN KEY 
	REFERENCES Composition(ID)
	ON DELETE CASCADE 
	ON UPDATE CASCADE,

	ID_Warehouse UNIQUEIDENTIFIER NOT NULL
	CONSTRAINT FK_Warehouse FOREIGN KEY 
	REFERENCES Warehouse(ID)
	ON DELETE CASCADE 
	ON UPDATE CASCADE,
);