USE MusicShop;

CREATE TABLE Composition
(
	ID UNIQUEIDENTIFIER DEFAULT NEWID()
	CONSTRAINT PK_Composition PRIMARY KEY,

	SerialNumber VARCHAR(255) NOT NULL,

	ID_Composer UNIQUEIDENTIFIER NOT NULL
	CONSTRAINT FK_Composer FOREIGN KEY 
	REFERENCES Composer(ID)
	ON DELETE CASCADE 
	ON UPDATE CASCADE,

	[Name] VARCHAR(50) NOT NULL,
	Duration INT NOT NULL,

	ID_Album UNIQUEIDENTIFIER NOT NULL
	CONSTRAINT FK_Album FOREIGN KEY 
	REFERENCES Album(ID)
	ON DELETE CASCADE 
	ON UPDATE CASCADE,

	ID_StorageMedium UNIQUEIDENTIFIER NOT NULL
	CONSTRAINT FK_StorageMedium FOREIGN KEY 
	REFERENCES StorageMedium(ID)
	ON DELETE CASCADE 
	ON UPDATE CASCADE,

	ID_Country UNIQUEIDENTIFIER NOT NULL
	CONSTRAINT FK_Country FOREIGN KEY 
	REFERENCES Country(ID)
	ON DELETE CASCADE 
	ON UPDATE CASCADE,

	ID_Genre UNIQUEIDENTIFIER NOT NULL
	CONSTRAINT FK_Genre FOREIGN KEY 
	REFERENCES Genre(ID)
	ON DELETE CASCADE 
	ON UPDATE CASCADE,

	Price FLOAT NOT NULL,
);

ALTER TABLE Composition
ADD CONSTRAINT u_CompositionSerialNumber UNIQUE(SerialNumber);