USE MusicShop;

CREATE TABLE Audit (
    ID UNIQUEIDENTIFIER DEFAULT NEWID()
	CONSTRAINT PK_Audit PRIMARY KEY,
    TableName VARCHAR(50) NOT NULL,
	Oper VARCHAR(15) NOT NULL,
	OldRec [XML] NULL,
	NewRec [XML] NULL,
	UserName VARCHAR(50) NOT NULL,
	DateCh DATETIME NULL
);