CREATE FUNCTION dbo.fGenreID
(
	@GenreName VARCHAR(50)
)
RETURNS UNIQUEIDENTIFIER
AS
BEGIN
	DECLARE @ID_Genre UNIQUEIDENTIFIER = 
			(SELECT TOP 1 ID
			FROM Genre
			WHERE [Name] = @GenreName);
	RETURN @ID_Genre;
END;